//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hotelreservation
{
    using System;
    using System.Collections.Generic;
    
    public partial class booking
    {
        public string bookingid { get; set; }
        public string roomid { get; set; }
        public string roomno { get; set; }
        public string name { get; set; }
        public string passportno { get; set; }
        public string email { get; set; }
        public System.DateTime datecheckin { get; set; }
        public System.DateTime datecheckout { get; set; }
        public Nullable<int> noofpeople { get; set; }
        public string Phone { get; set; }
    
        public virtual roomfacility roomfacility { get; set; }
    }
}
