//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hotelreservation
{
    using System;
    using System.Collections.Generic;
    
    public partial class login
    {
        public login()
        {
            this.userdetails = new HashSet<userdetail>();
        }
    
        public string userid { get; set; }
        public string passsword { get; set; }
    
        public virtual ICollection<userdetail> userdetails { get; set; }
    }
}
