//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hotelreservation
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HotelReservationEntities3 : DbContext
    {
        public HotelReservationEntities3()
            : base("name=HotelReservationEntities3")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<availablity> availablities { get; set; }
        public virtual DbSet<booking> bookings { get; set; }
        public virtual DbSet<login> logins { get; set; }
        public virtual DbSet<roomfacility> roomfacilities { get; set; }
        public virtual DbSet<userdetail> userdetails { get; set; }
    }
}
