//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hotelreservation
{
    using System;
    using System.Collections.Generic;
    
    public partial class roomfacility
    {
        public roomfacility()
        {
            this.availablities = new HashSet<availablity>();
            this.bookings = new HashSet<booking>();
        }
    
        public string roomid { get; set; }
        public int roomrent { get; set; }
        public int roomsavailable { get; set; }
    
        public virtual ICollection<availablity> availablities { get; set; }
        public virtual ICollection<booking> bookings { get; set; }
    }
}
